name: dimundi-proxy

services:
  proxy:
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
        bind:
          create_host_path: false
      - ./acme:/var/www/certbot:ro
      - ./mail-conf:/etc/nginx/mail-conf:ro
      - ./letsencrypt:/etc/letsencrypt:ro

  certbot:
    image: certbot/certbot:v5.8.0
    profiles: [tools]
    volumes:
      - ./acme:/var/www/certbot
      - ./letsencrypt:/etc/letsencrypt
