enabled = true;
sign_authenticated = true;
sign_local = false;
try_fallback = false;
use_domain = "header";
use_redis = false;
use_esld = true;
allow_username_mismatch = true;
check_pubkey = true;
domain {
    dimundi.com {
        path = "/tmp/docker-mailserver/rspamd/dkim/rsa-2048-dimundi2026-dimundi.com.private.txt";
        selector = "dimundi2026";
    }
    dimundi.pl {
        path = "/tmp/docker-mailserver/rspamd/dkim/rsa-2048-dimundi2026-dimundi.pl.private.txt";
        selector = "dimundi2026";
    }
}
